config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'statics#home', as: 'home'
  get  'help' => 'statics#help'
  get  'about' => 'statics#about'
  get  'contact' => 'statics#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :rooms do
    member do
      get :add_participant
      get :remove_user
    end
  end
  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
	#has_many :rooms
	has_and_belongs_to_many :rooms
	has_secure_password
	before_save { self.email=email.downcase }
	validates :name, presence: { message: " is required" }
	validates :email, uniqueness: { case_sensitive: false, message: "already in use" } 
	validates :username, presence: { message: " is required" }
 	attr_accessor :remember_token
 	

 	validates :password, presence: true, length: { minimum: 7 }, allow_nil: true
 	#attr_accessor :password, :password_confirmation


	# def initialize(attributes = {})
	# 	@name = attributes[:name]
	# 	@address = attributes[:address]
	# 	@email = attributes[:email]
	# 	@password = attributes[:password]
	# end
	class << self
		def digest(string)
			cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
			BCrypt::Password.create(string, cost: cost)
		end

		def new_token
			SecureRandom.urlsafe_base64
		end
	end
	def remember 
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show, :index, :edit, :update]
	before_action :correct_user, only: [:show, :edit, :update]
	before_action :administrator, only: [:index]
	def index
		@users=User.all
	end

	def show 
		@user = User.find_by_id(params[:id])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if(@user.save)
			flash[:success] = "Welcome to GameHubOne!"
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find_by_id(params[:id])
	end

	def update
		@user = User.find_by_id(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find_by_id(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def logged_in_user
    	unless logged_in?
    		store_location
    		flash[:danger] = "Please log in."
    		redirect_to login_url
    	end
    end

    def correct_user
    	@user = User.find_by_id(params[:id])
    	unless current_user?(@user) or admin?
    		flash[:danger] = "Invalid page"
    		redirect_to(home_url)
    	end
    	
    end

    def administrator
    	unless admin?
    		flash[:danger] = "Invalid page"
    		redirect_to(home_url)
    	end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
	
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="col-md-6 col-md-offset-3", style="margin-bottom:10">
		
		<%= f.label 'Name*'%><br>
		<%= f.text_field(:name, {:class => 'form-control'}) %>
		<p></p>
		<%=f.label 'Username*'%><br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
		<p></p>
		<%=f.label 'Email*'%><br>
		<%= f.email_field(:email, {:class => 'form-control'}) %>
		<p></p>
		<%=f.label 'Password*'%><br>
		<%= f.password_field(:password, {:class => 'form-control'}) %>
		<p></p>
		<%=f.label 'Confirm Password*'%><br>
		<%= f.password_field(:password_confirmation, {:class => 'form-control'}) %>
		<p></p>

		<div style="text-align:center;">
			<%= f.submit yield(:button_text), {:class => 'btn btn-success'} %>
		</div>

	</div>
<% end %>

app/views/users/edit.html.erb
<h1 style="text-align:center">Update your profile</h1>
<% provide(:button_text, 'Save changes') %>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class="page-header">
    <h1>Users</h1>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table">
    	    <thead>
          		<tr>
               		<th>#</th>
               		<th>Name</th>
               		<th>Username</th>
               		<th>Email</th>
           		</tr>
           	</thead>
	        <tbody>
            	<% @users.each do |user| %>
            		<tr>
            			<td><%= user.id %></td>
            			<td><%= user.name %></td>
            			<td><%= user.username %></td>
            			<td><%= user.email %></td>
            		</tr>
            	<% end %>
            </tbody>
        </table>
    </div>
</div>
        

app/views/users/new.html.erb
<h1 style="text-align:center;">Create User</h1>	
<% provide(:button_text, 'Create Account') %>

<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<p><%= @user.email %></p>
<p><%= @user.name %></p>
<% if admin? %>
	<%= link_to "Back to users", users_path, class: 'btn btn-default' %>
<% end %>
<%= link_to "Edit", edit_user_path(@user), :class => 'btn btn-warning' %>
<%= link_to "Delete", user_path(@user), 
					method: :delete,
					data: {confirm: 'Are you sure?'},
					:class => 'btn btn-danger' %>