config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'statics#home', as: 'home'
  get  'help' => 'statics#help'
  get  'about' => 'statics#about'
  get  'contact' => 'statics#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :rooms do
    member do
      get :add_participant
      get :remove_user
    end
  end
  get '*path' => redirect('/')
end

app/models/room.rb
class Room < ApplicationRecord
	#belongs_to :user
	has_and_belongs_to_many :users
	has_one :owner
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :logged_in_user, only: [:show, :index, :edit, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :valid_page, only: [:show]


  def index
    @rooms= current_user.rooms.all
  end

  def show 
    @room = Room.find_by_id(params[:id])
  end
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @user = current_user
    @room.owner=@user
    #@room.participants.push(@user)
    if(!admin? and @user.rooms_owned.length>=3)
      flash[:danger] = "Only 3 rooms may be owned at once, please delete a room and try again!"
      redirect_to rooms_path
    elsif(@room.save)
      flash[:success] = "Successfully created room!"

      #@owned=current_user.rooms_owned.push(@room.id)
      #current_user.update_attribute(:rooms_owned, current_user.rooms_owned.push(@room.id))
      #current_user.update_attribute(:rooms_in, current_user.rooms_in.push(@room.id))
      #render plain:current_user.inspect
      redirect_to @room
    else
      render 'new'
    end
  end

  def destroy
    @room = Room.find_by_id(params[:id])
    #@owner=User.find_by_id(@room.owne
    @owner=@room.owner
    #@owner.update_attribute(:rooms_owned, @owner.rooms_owned-[@room.id])
    #remove_participants(@room.id)
    @room.destroy
    redirect_to rooms_path
  end

  def edit
    @room = Room.find_by_id(params[:id])
  end

  def update
    @room = Room.find_by_id(params[:id])
    if @room.update_attributes(room_params)
      flash[:success] = "Room updated"
      redirect_to @room
    else
      render 'edit'
    end
  end


  private def room_params
    params.require(:room).permit(:name, :private)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @room= Room.find_by_id(params[:id])
    unless @room.owner==current_user.id or admin?
      flash[:danger] = "Invalid page"
      redirect_to(home_url)
    end
  end
  def valid_page
    @room= Room.find_by_id(params[:id])
    if(@room==nil)
      flash[:danger] = "Invalid page"
      redirect_to(home_url)
    end
  end
  def add_participant
    @user=current_user
    @room=Room.find_by_id(params[:id])
    @room.update_attribute(:participants, @room.participants.push(@user.id))
    @user.update_attribute(:rooms_in, @user.rooms_in.push(@room.id))
    render 'show'
  end

  def remove_participants(id)
    @room=Room.find_by_id(id)
    @room.participants.each do |user_id|
      @user=User.find_by_id(user_id)
      remove_participant(@room, @user)
    end
  end
  def remove_user
    @room=Room.find_by_id(params[:id])
    remove_participant(@room, current_user)
    render 'show'
  end
  def remove_participant(room, user)
    room.update_attribute(:participants, room.participants-[user.id])
    user.update_attribute(:rooms_in, user.rooms_in-[room.id])
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper

	def remove_participants(id)
		@room=Room.find_by_id(id)

		@room.participants.each do |user|
			user.update_attribute(:rooms_in, user.rooms_in-[id])
		end
	end

	#def add_participant(room, user)
	#	room.update_attribute(:participants, room.participants.push(user.id))
	#	user.update_attribute(:rooms_in, user.rooms_in.push(room.id))
	#end
end

app/views/rooms/edit.html.erb
<% provide(:title, "Edit Room") %>
<h1 style="text-align:center;">Create Room</h1>	

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @room do |f| %>  <!--Submits to the room create method-->

      <%= f.label 'Room name*' %>
      <%= f.text_field :name, class: 'form-control' %>
      <p></p>
  
      <%= f.check_box :private %>

      <%= f.label 'Private?', :as => :boolean, :label => false, :inline_label => true%>
    
 
      <div style="text-align:center;">
      <%= f.submit "Save Changes", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<% provide(:title, 'Rooms') %>

<h3>Your Rooms</h3>
<div class="row">
    <div class="col-md-6">
        <table class="table">
    	    <thead>
          		<tr>
               		<th>#</th>
               		<th>Name</th>
               		<th>Owner</th>
               		<% if admin? %>
            			<th>Recent Activity</th>
            		<% end %>
               		
           		</tr>
           	</thead>
	        <tbody>
            	<% @rooms.each do |room| %>
            		<tr>
            			<% owner = room.owner %>
            			<td><%= room.id %></td>
            			<td><%= link_to room.name, room %></td>
            			<td><%= link_to owner.username, owner %></td>
            			<% if admin? %>
            				<td><%= room.updated_at %></td>
            			<% end %>

            		</tr>
            	<% end %>
            	<% current_user.rooms_in.each do |room_id| %>
            		<tr>
            			<% room = Room.find_by_id(room_id) %>
            			<% owner = User.find_by_id(room.owner) %>
            			<td><%= room_id %></td>
            			<td><%= link_to room.name, room %></td>
            			<td><%= link_to owner.username, owner %></td>
            			<% if admin? %>
            				<td><%= room.updated_at %></td>
            			<% end %>

            		</tr>
            	<% end %>
            </tbody>
        </table>
    </div>
</div>
<h3>Other Rooms</h3>
<div class="row">
    <div class="col-md-6">
        <table class="table">
    	    <thead>
          		<tr>
               		<th>#</th>
               		<th>Name</th>
               		<th>Owner</th>
               		<% if admin? %>
            			<th>Recent Activity</th>
            		<% end %>
           		</tr>
           	</thead>
	        <tbody>
            	<% @rooms.each do |room| %>
            		<% unless current_user.rooms_owned.include?(room.id) or current_user.rooms_in.include?(room.id) %>
            		<tr>
            			<% owner = User.find_by_id(room.owner) %>
            			<td><%= room.id %></td>
            			<td><%= link_to room.name, room %></td>
            			<td><%= link_to owner.username, owner %></td>
            			<% if admin? %>
            				<td><%= room.updated_at %></td>
            			<% end %>
            		</tr>
            		<% end %>
            	<% end %>
            </tbody>
        </table>
    </div>
</div>
        

app/views/rooms/new.html.erb
<% provide(:title, "Create Room") %>
<h1 style="text-align:center;">Create Room</h1>	

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @room do |f| %>  <!--Submits to the room create method-->

      <%= f.label 'Room name*' %>
      <%= f.text_field :name, class: 'form-control' %>
      <p></p>
  
      <%= f.check_box :private %>

      <%= f.label 'Private?', :as => :boolean, :label => false, :inline_label => true%>
    
 
      <div style="text-align:center;">
      <%= f.submit "Create room", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<h2><%= @room.name %>
	<% if @room.private %>
		(Private)
	<% end %>
</h2>
<%= debug @room %>
<p>Owner: <%= @room.owner%></p>
<% if current_user?(@room.owner) or admin? %>
	<%= link_to "Edit", edit_room_path(@room), :class => 'btn btn-default' %>
	<%= link_to "Delete", room_path(@room), 
					method: :delete,
					data: {confirm: 'Are you sure?'},
					:class => 'btn btn-danger' %>
<% end %>
<% if not current_user.rooms.include?(@room) and not current_user?(room.owner)%>
	<% if @room.private %>
		<%= link_to "Request to join room", room_path(@room), :class => 'btn btn-default' %>
	<% else %>
		<%= link_to "Join Room", add_participant_room_path(@room), :class => 'btn btn-default' %>
	<% end %>
<% elsif !current_user?(@room.owner)%>
	<%= link_to "Leave Room", remove_user_room_path(@room), :class => 'btn btn-danger' %>
<% end %>