config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'statics#home', as: 'home'
  get  'help' => 'statics#help'
  get  'about' => 'statics#about'
  get  'contact' => 'statics#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :rooms do
    member do
      get :add_participant
      get :remove_user
    end
  end
  get '*path' => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "styling.css" %>
<html>
  <head>
    <title>GameHubOne</title>
   
    <%= csrf_meta_tags %>
 	  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "styling.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  </head>

  <body>
    <div>
      <div class="navbar-wrapper">
        <nav class="navbar navbar-default navbar-static-top translucent">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">GameHubOne</a>
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul id="right-navbar" class="nav navbar-nav pull-right">
          <!-- <li class="active"><a href="#">Home</a></li> -->
                <% if logged_in? %>
                
               
                  <li><%= link_to "Create a Room", new_room_path %></li> 
                  <li><%= link_to "Rooms", rooms_path %></li>
        
                  <% if admin? %> 
                    <li><%= link_to "Users", users_path %></li> 
                  <% end %>
              
                
                  <li class="dropdown">
                     <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                    <strong><%= current_user.email %></strong><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li> 
                      <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Log in", login_path %></li> <!--Returns /user/new-->
                  <li><%= link_to "Create Account", signup_path %></li> 
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  <p> <br> <br> <br></p> <!--Add space so content doesn't interfere with the footer-->
  </body>
  <footer class="footer">
    <nav class="navbar navbar-default navbar-fixed-bottom">
      <div class="navbar-footer container">
        <ul class="nav navbar-nav navbar-left navbar-footer">
          <li><%= link_to "About", about_path %></li> 
          <li><%= link_to "Contact", contact_path %></li> 
          <li><%= link_to "Help", help_path %></li> 
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= link_to image_tag("rails.png", alt: "Rails logo", width: "60px"),
          'http://rubyonrails.org/' %>
        </ul>
      </div>
    </nav>
  </footer>
</html>